""" Module providing constants """

# Notification types
NOTIFY_NEVER = 1
NOTIFY_CONNECT_FIRST_TIME = 2
NOTIFY_CONNECT_FIRST_TIME_OR_IP_HOPE = 3
NOTIFY_CONNECT_EACH_TIME = 4
NOTIFY_CONNECT_EACH_TIME_WITH_MAX_PER_DAY = 5
NOTIFY_CONNECT_EACH_TIME_WITH_MAX_PER_DAY_WITH_INTERMITTENT = 6

# Notifications related consts
DEFAULT_NOTIFICATION_STRING = "Device got connected Name: {NAME}, IP: {IP}, MAC: {MAC}, Count: {COUNT}"
DND_NOTIFY_START_HOUR = 22
DND_NOTIFY_END_HOUR = 8
MAX_NOTIFY_COUNT_PER_DAY = 5

# Logs file purge details
PURGE_LOGS_AFTER_DAYS = 7

# syslog consts
SYSLOG_SOCKET_RECEIVE_BUFFER = 4096
SYSLOG_SERVER_IP = "0.0.0.0"
SYSLOG_SERVER_PORT = 5142

# file consts
APP_CONFIG_FILE = 'config.yaml'
JSON_FILE_UNIFI_DHCPACK_FILE = 'unifi_dhcpack_status.json'
JSON_FILE_NOTIFICATION_HIST_FILE  = 'notification_history.json'
